Declare @Codtra varchar (100)

set @Codtra = 'SAR_FC'

-- Maestro
UPDATE INMTRE SET
INMTRE_CODTRA = REPLACE(INMTRE_CODTRA,'SAR_','USR_')
WHERE
INMTRE_CODTRA = @Codtra 

UPDATE INMTRI SET
INMTRI_CODTRA = REPLACE(INMTRI_CODTRA,'SAR_','USR_')
WHERE
INMTRI_CODTRA = @Codtra

UPDATE INMTRO SET
INMTRO_CODTRA = REPLACE(INMTRO_CODTRA,'SAR_','USR_')
WHERE
INMTRO_CODTRA = @Codtra


-- Objetos
UPDATE INMOBJ SET
INMOBJ_CODTRA = REPLACE(INMOBJ_CODTRA,'SAR_','USR_')
WHERE
INMOBJ_CODTRA = @Codtra

UPDATE INMOBH SET
INMOBH_CODTRA = REPLACE(INMOBH_CODTRA,'SAR_','USR_')
WHERE
INMOBH_CODTRA = @Codtra

UPDATE INMOBC SET
INMOBC_CODTRA = REPLACE(INMOBC_CODTRA,'SAR_','USR_')
WHERE
INMOBC_CODTRA = @Codtra

UPDATE INMOBI SET
INMOBI_CODTRA = REPLACE(INMOBI_CODTRA,'SAR_','USR_')
WHERE
INMOBI_CODTRA = @Codtra

UPDATE INMOBW SET
INMOBW_CODTRA = REPLACE(INMOBW_CODTRA,'SAR_','USR_')
WHERE
INMOBW_CODTRA = @Codtra

UPDATE INMOC1 SET
INMOC1_CODTRA = REPLACE(INMOC1_CODTRA,'SAR_','USR_')
WHERE
INMOC1_CODTRA = @Codtra

UPDATE INMOC2 SET
INMOC2_CODTRA = REPLACE(INMOC2_CODTRA,'SAR_','USR_')
WHERE
INMOC2_CODTRA = @Codtra

UPDATE INMOC3 SET
INMOC3_CODTRA = REPLACE(INMOC3_CODTRA,'SAR_','USR_')
WHERE
INMOC3_CODTRA = @Codtra

UPDATE INMOT1 SET
INMOT1_CODTRA = REPLACE(INMOT1_CODTRA,'SAR_','USR_')
WHERE
INMOT1_CODTRA = @Codtra

UPDATE INMOT2 SET
INMOT2_CODTRA = REPLACE(INMOT2_CODTRA,'SAR_','USR_')
WHERE
INMOT2_CODTRA = @Codtra

