UPDATE STMPDH SET 
STMPDH_ARTCOD=REPLICATE(' ',4-LEN(STMPDH_ARTCOD))+STMPDH_ARTCOD , 
STMPDH_ARTCOQ=REPLICATE(' ',4-LEN(STMPDH_ARTCOD))+STMPDH_ARTCOD , 
STMPDH_ARTDIS=REPLICATE(' ',4-LEN(STMPDH_ARTCOD))+STMPDH_ARTCOD , 
STMPDH_RUBR01=REPLICATE(' ',4-LEN(STMPDH_ARTCOD))+STMPDH_ARTCOD
where STMPDH_TIPPRO in ('P','PN') AND LEN(STMPDH_ARTCOD)<4