SELECT  *  FROM PVRMVH WHERE PVRMVH_MODFOR='PV'AND PVRMVH_CODFOR='FA' AND PVRMVH_NROFOR=	371000001
SELECT  *  FROM PVRMVI WHERE PVRMVI_MODFOR='PV'AND PVRMVI_CODFOR='FA' AND PVRMVI_NROFOR=	371000001
SELECT  *  FROM PVRMVC WHERE PVRMVC_MODFOR='PV'AND PVRMVC_CODFOR='FA' AND PVRMVC_NROFOR=	371000001
SELECT  *  FROM PVRMVD WHERE PVRMVD_MODFOR='PV'AND PVRMVD_CODFOR='FA' AND PVRMVD_NROFOR=	371000001
SELECT  *  FROM PVRMVG WHERE PVRMVG_MODFOR='PV'AND PVRMVG_CODFOR='FA' AND PVRMVG_NROFOR=	371000001
SELECT  *  FROM PVRMVP  WHERE PVRMVP_MODFOR='PV'AND PVRMVP_CODFOR='FA' AND PVRMVP_NROFOR=	371000001

SELECT  *  FROM PVRMVC
WHERE
PVRMVC_MODFOR='PV' AND
PVRMVC_CODFOR='OP' AND
PVRMVC_NROFOR =372000001

SELECT  *  FROM PVROPH
WHERE
PVROPH_MODFOR='PV' AND
PVROPH_CODFOR='OP' AND
PVROPH_NROFOR =372000001
