Select  
VTRMVH_MODFOR MODULO,
VTRMVH_CODFOR FORMULARIO,
VTRMVH_NROFOR ,
VTRMVH_FCHMOV FECHA1,
CONVERT(VARCHAR,VTRMVH_FECALT,112) [FECHA ALTA CONV],
CONVERT(VARCHAR,VTRMVH_FCHMOV,103) FECHA,
VTRMVH_NROCTA CLIENTE,
(select 
top 1 GRTVAL_VALORI  
From
GRTVAL 
Where
GRTVAL_CODCOF ='USD' And
GRTVAL_FECCAL <VTRMVH_FECMOD 
order by GRTVAL_FECCAL desc),
convert(numeric(10,2),

(select 
top 1 GRTVAL_VALORI  
From
GRTVAL 
Where
GRTVAL_CODCOF ='USD' And
GRTVAL_FECCAL <VTRMVH_FCHMOV
order by GRTVAL_FECCAL desc)*VTRMVH_NROFOR ),
floor(
convert(numeric(10,2),

(select 
top 1 GRTVAL_VALORI  
From
GRTVAL 
Where
GRTVAL_CODCOF ='USD' And
GRTVAL_FECCAL <VTRMVH_FCHMOV
order by GRTVAL_FECCAL desc)*VTRMVH_NROFOR ))

From 
VTRMVH  
Where 
(Convert(Varchar,VTRMVH_FCHMOV,112) Between '20100426' And '20200426' And
(VTRMVH_NROCTA='000002' Or VTRMVH_NROCTA='000013') )
Order By 
CLIENTE asc

