SELECT 
a.VTRMVH_NROCTA ,C.VTMCLH_NOMBRE , 
A.VTRMVH_NROSUB ,D.VTMCLH_NOMBRE,
a.VTRMVH_VNDDOR,VTTVND_DESCRP ,
a.VTRMVH_MODFOR,a.VTRMVH_CODFOR,a.VTRMVH_NROFOR ,b.VTRMVC_IMPNAC,
*

From
VTRMVH A left Outer JOIN VTRMVC  B ON
b.VTRMVC_MODFOR=A.VTRMVH_MODFOR AND
b.VTRMVC_CODFOR=A.VTRMVH_CODFOR AND
b.VTRMVC_NROFOR=A.VTRMVH_NROFOR


Inner Join VTMCLH C On
A.VTRMVH_NROCTA=C.VTMCLH_NROCTA 
Inner Join VTTVND On
A.VTRMVH_VNDDOR=VTTVND_VNDDOR 
INNER JOIN VTMCLH D ON
A.VTRMVH_NROSUB = D.VTMCLH_NROCTA 

Where
A.VTRMVH_MODFOR='VT' AND
A.VTRMVH_CODFOR='FA0001'  
order by  B.VTRMVC_IMPNAC desc
