SELECT *  FROM CJRMVH
WHERE
CJRMVH_MODFOR='CJ' AND
CJRMVH_CODFOR='RC0001' AND
CJRMVH_NROFOR=36

SELECT 
CJRMVI_FCHVNC ,
CJRMVI_NROCVT,
CJRMVI_CTACTE,CJRMVI_NROINT,
CJRMVI_TIPCPT,CJRMVI_CODCPT,CJRMVI_CHEQUE,
SUM(CJRMVI_IMPDEB-CJRMVI_IMPHAB)  FROM CJRMVI
WHERE
CJRMVI_NROCVT IS NOT NULL
GROUP BY 
CJRMVI_FCHVNC ,
CJRMVI_NROCVT,
CJRMVI_CTACTE,CJRMVI_NROINT,
CJRMVI_TIPCPT,CJRMVI_CODCPT,CJRMVI_CHEQUE
HAVING 
SUM(CJRMVI_IMPDEB-CJRMVI_IMPHAB)>0
ORDER BY CJRMVI_FCHVNC ASC