SELECT GETDATE()
SELECT CONVERT(VARCHAR,GETDATE(),112)
SELECT YEAR(GETDATE())*10000+MONTH(GETDATE())*100+DAY(GETDATE())
SELECT DATEADD(yy,-5,GETDATE())
SELECT ROUND((DATEDIFF(N, GETDATE(),'20130615') )/1440,2)
SELECT DATEPART(DY,GETDATE())
SELECT DATENAME(WEEKDAY ,GETDATE())

SELECT DATEADD(D,-(DAY(GETDATE())-1),GETDATE())


SELECT DATEADD(D,-DAY(GETDATE()),DATEADD(M,1,GETDATE()))

