declare @CODEMP varchar(10)

select @CODEMP = 'CONSULT'


update CWPARAMETERS
set
COMPANYNAME = @CODEMP
where
COMPANYNAME <> @CODEMP and
not EXISTS
(select 1 from CWPARAMETERS P1 where
P1.PARAMNAME = CWPARAMETERS.PARAMNAME and
P1.COMPANYNAME = @CODEMP)

delete CWPARAMETERS
where
COMPANYNAME <> @CODEMP and
EXISTS
(select 1 from CWPARAMETERS p1 where
p1.paramname = CWPARAMETERS.PARAMNAME and
p1.COMPANYNAME = @CODEMP)

update CWPARAMETERS 
set
COMPANYNAME = @CODEMP
where
COMPANYNAME <> @CODEMP