INSERT INTO CWTMTRANSFER
(RANDOMKEY,
KEYDATE,
MainTableName,
MainTableKeyValues,
OrderNumber,
TransactionDescription,
RelatedTables,
OperationType,
MainTableKeyNames,
MainTableKeyDatatypes,
TransferBatch,
TABLE_UPDATE,
ISRERECEPTION,
CWTMTR_FECALT,
CWTMTR_FECMOD,
CWTMTR_USERID,
CWTMTR_ULTOPR,
CWTMTR_DEBAJA,
CWTMTR_OALIAS)

SELECT
REPLACE(NEWID(),'-','') "RANDOMKEY",
FCRMVH_FECALT "KEYDATE",
'FCRMVH' "MainTableName",
CONVERT(VARCHAR,FCRMVH_CODEMP) + '#' + CONVERT(VARCHAR,FCRMVH_MODFOR) + '#' + CONVERT(VARCHAR,FCRMVH_CODFOR)+ '#' + CONVERT(VARCHAR,FCRMVH_NROFOR)+'#' "MainTableKeyValues",
1 "OrderNumber",
CONVERT(VARCHAR,FCRMVH_CODEMP) + '#' + CONVERT(VARCHAR,FCRMVH_MODFOR) + '#' + CONVERT(VARCHAR,FCRMVH_CODFOR)+ '#' + CONVERT(VARCHAR,FCRMVH_NROFOR)+'#'  "TransactionDescription",
'FCRMVH#FCRMVI#FCRMVD#FCRMVP#FCRMVA#FCRMVX#FCRMVG#' "RelatedTables",
'A' "OperationType",
'FCRMVH_CODEMP#FCRMVH_MODFOR#FCRMVH_CODFOR#FCRMVH_NROFOR#' "MainTableKeyNames",
'12#12#12#4#' "MainTableKeyDatatypes",
NULL "TransferBatch",
'' "TABLE_UPDATE",
NULL "ISRERECEPTION",
FCRMVH_FECALT "CWTMTR_FECALT",
FCRMVH_FECMOD "CWTMTR_FECMOD",
'GSA_MIG' "CWTMTR_USERID",
'A' "CWTMTR_ULTOPR",
'N' "CWTMTR_DEBAJA",
'FCRMVH' "CWTMTR_OALIAS"
FROM FCRMVH
left JOIN CWTMTRANSFER ON
FCRMVH_CODEMP = DBO.cwFncTRSplit(MainTableKeyValues, '#',1) AND
FCRMVH_MODFOR = DBO.cwFncTRSplit(MainTableKeyValues, '#',2) AND
FCRMVH_CODFOR = DBO.cwFncTRSplit(MainTableKeyValues, '#',3) AND
FCRMVH_NROFOR = DBO.cwFncTRSplit(MainTableKeyValues, '#',4) AND
MAINTABLEname = 'fcrmvh'
WHERE
MainTableKeyValues IS NULL

UNION

SELECT
REPLACE(NEWID(),'-','') "RANDOMKEY",
(SELECT FCRMVH_FECALT FROM FCRMVH
WHERE
FCRMVH_CODEMP = VTRMVH_CODEMP AND
FCRMVH_MODFOR = VTRMVH_MODFOR AND
FCRMVH_CODFOR  = VTRMVH_CODFOR AND
FCRMVH_NROFOR = VTRMVH_NROFOR ) "KEYDATE",
'VTRMVH' "MainTableName",
CONVERT(VARCHAR,vtrmvh_CODEMP) + '#' + CONVERT(VARCHAR,vtrmvh_MODFOR) + '#' + CONVERT(VARCHAR,vtrmvh_CODFOR)+ '#' + CONVERT(VARCHAR,vtrmvh_NROFOR)+'#' "MainTableKeyValues",
2 "OrderNumber",
CONVERT(VARCHAR,vtrmvh_CODEMP) + '#' + CONVERT(VARCHAR,vtrmvh_MODFOR) + '#' + CONVERT(VARCHAR,vtrmvh_CODFOR)+ '#' + CONVERT(VARCHAR,vtrmvh_NROFOR)+'#'  "TransactionDescription",
'VTRMVH#VTRMVI#VTRMVD#VTRMVG#VTRMVP#VTRMVT#VTRMVC#' "RelatedTables",
'A' "OperationType",
'FCRMVH_CODEMP#FCRMVH_MODFOR#FCRMVH_CODFOR#FCRMVH_NROFOR#' "MainTableKeyNames",
'12#12#12#4#' "MainTableKeyDatatypes",
NULL "TransferBatch",
'' "TABLE_UPDATE",
NULL "ISRERECEPTION",
vtrmvh_FECALT "CWTMTR_FECALT",
vtrmvh_FECMOD "CWTMTR_FECMOD",
'GSA_MIG' "CWTMTR_USERID",
'A' "CWTMTR_ULTOPR",
'N' "CWTMTR_DEBAJA",
'vtrmvh' "CWTMTR_OALIAS"
FROM vtrmvh
left JOIN CWTMTRANSFER ON
vtrmvh_CODEMP = DBO.cwFncTRSplit(MainTableKeyValues, '#',1) AND
vtrmvh_MODFOR = DBO.cwFncTRSplit(MainTableKeyValues, '#',2) AND
vtrmvh_CODFOR = DBO.cwFncTRSplit(MainTableKeyValues, '#',3) AND
vtrmvh_NROFOR = DBO.cwFncTRSplit(MainTableKeyValues, '#',4) AND
MAINTABLEname IN ('vtrmvh','VTRRCH')
WHERE
MainTableKeyValues IS NULL

UNION 

SELECT
REPLACE(NEWID(),'-','') "RANDOMKEY",
ISNULL((SELECT FCRMVH_FECALT FROM FCRMVH
WHERE
FCRMVH_CODEMP = CJRMVH_CODEMP AND
FCRMVH_MODFOR = 'VT' AND
FCRMVH_CODFOR  = CJRMVH_CODFOR AND
FCRMVH_NROFOR = CJRMVH_NROFOR ),CJRMVH_fECALT) "KEYDATE",
'CJRMVH' "MainTableName",
CONVERT(VARCHAR,CJRMVH_CODEMP) + '#' + CONVERT(VARCHAR,CJRMVH_MODFOR) + '#' + CONVERT(VARCHAR,CJRMVH_CODFOR)+ '#' + CONVERT(VARCHAR,CJRMVH_NROFOR)+'#' "MainTableKeyValues",
(CASE WHEN NOT EXISTS (SELECT 1 FROM FCRMVH WHERE
FCRMVH_CODEMP = CJRMVH_CODEMP AND
FCRMVH_MODFOR = 'VT' AND
FCRMVH_CODFOR = CJRMVH_CODFOR AND
FCRMVH_NROFOR = FCRMVH_NROFOR) THEN 1 ELSE 3 END) "OrderNumber",
CONVERT(VARCHAR,CJRMVH_CODEMP) + '#' + CONVERT(VARCHAR,CJRMVH_MODFOR) + '#' + CONVERT(VARCHAR,CJRMVH_CODFOR)+ '#' + CONVERT(VARCHAR,CJRMVH_NROFOR)+'#'  "TransactionDescription",
'CJRMVH#CJRMVI#CJRMVD#CJRMVG#' "RelatedTables",
'A' "OperationType",
'CJRMVH_CODEMP#CJRMVH_MODFOR#CJRMVH_CODFOR#CJRMVH_NROFOR#' "MainTableKeyNames",
'12#12#12#4#' "MainTableKeyDatatypes",
NULL "TransferBatch",
'' "TABLE_UPDATE",
NULL "ISRERECEPTION",
CJRMVH_FECALT "CWTMTR_FECALT",
CJRMVH_FECMOD "CWTMTR_FECMOD",
'GSA_MIG' "CWTMTR_USERID",
'A' "CWTMTR_ULTOPR",
'N' "CWTMTR_DEBAJA",
'CJRMVH' "CWTMTR_OALIAS"
FROM CJRMVH
left JOIN CWTMTRANSFER ON
CJRMVH_CODEMP = DBO.cwFncTRSplit(MainTableKeyValues, '#',1) AND
CJRMVH_MODFOR = DBO.cwFncTRSplit(MainTableKeyValues, '#',2) AND
CJRMVH_CODFOR = DBO.cwFncTRSplit(MainTableKeyValues, '#',3) AND
CJRMVH_NROFOR = DBO.cwFncTRSplit(MainTableKeyValues, '#',4) AND
MAINTABLEname = 'CJRMVH'
WHERE
MainTableKeyValues IS NULL

UNION

SELECT
REPLACE(NEWID(),'-','') "RANDOMKEY",
(SELECT FCRMVH_FECALT FROM FCRMVH
WHERE
FCRMVH_EMPOST = STRMVH_CODEMP AND
FCRMVH_MODOST = STRMVH_MODFOR AND
FCRMVH_CODOST = STRMVH_CODFOR AND
FCRMVH_NROOST = STRMVH_NROFOR ) "KEYDATE",
'STRMVH' "MainTableName",
CONVERT(VARCHAR,STRMVH_CODEMP) + '#' + CONVERT(VARCHAR,STRMVH_MODFOR) + '#' + CONVERT(VARCHAR,STRMVH_CODFOR)+ '#' + CONVERT(VARCHAR,STRMVH_NROFOR)+'#' + CONVERT(VARCHAR, STRMVH_SUCURS) +'#'  "MainTableKeyValues",
4 "OrderNumber",
CONVERT(VARCHAR,STRMVH_CODEMP) + '#' + CONVERT(VARCHAR,STRMVH_MODFOR) + '#' + CONVERT(VARCHAR,STRMVH_CODFOR)+ '#' + CONVERT(VARCHAR,STRMVH_NROFOR)+'#'  "TransactionDescription",
'STRMVH#STRMVI#' "RelatedTables",
'A' "OperationType",
'STRMVH_CODEMP#STRMVH_MODFOR#STRMVH_CODFOR#STRMVH_NROFOR#STRMVH_SUCURS#' "MainTableKeyNames",
'12#12#12#4#12#' "MainTableKeyDatatypes",
NULL "TransferBatch",
'' "TABLE_UPDATE",
NULL "ISRERECEPTION",
STRMVH_FECALT "CWTMTR_FECALT",
STRMVH_FECMOD "CWTMTR_FECMOD",
'GSA_MIG' "CWTMTR_USERID",
'A' "CWTMTR_ULTOPR",
'N' "CWTMTR_DEBAJA",
'STRMVH' "CWTMTR_OALIAS"
FROM STRMVH
left JOIN CWTMTRANSFER ON
STRMVH_CODEMP = DBO.cwFncTRSplit(MainTableKeyValues, '#',1) AND
STRMVH_MODFOR = DBO.cwFncTRSplit(MainTableKeyValues, '#',2) AND
STRMVH_CODFOR = DBO.cwFncTRSplit(MainTableKeyValues, '#',3) AND
STRMVH_NROFOR = DBO.cwFncTRSplit(MainTableKeyValues, '#',4) AND
MAINTABLEname = 'STRMVH'
WHERE
MainTableKeyValues IS NULL

ORDER BY 2,4

