declare @@MOD varchar(2), @@MOD_CJ varchar(2), @@COD varchar(6), @@NRO int

select
@@MOD = 'PV',
@@MOD_CJ = 'CJ',
@@COD = 'OP',
@@NRO = 5610


UPDATE CJRMVH SET CJRMVH_MODFOP=NULL, CJRMVH_CODFOP=NULL, CJRMVH_NROFOP=NULL where CJRMVH_MODFOR = @@MOD_CJ and CJRMVH_CODFOR = @@COD and CJRMVH_NROFOR = @@NRO
UPDATE PVRMVH SET PVRMVH_MODDCR=NULL, PVRMVH_CODDCR=NULL, PVRMVH_NRODCR=NULL where PVRMVH_MODFOR = @@MOD and PVRMVH_CODFOR = @@COD and PVRMVH_NROFOR = @@NRO

delete PVROPH where PVROPH_MODFOR = @@MOD and PVROPH_CODFOR = @@COD and PVROPH_NROFOR = @@NRO
delete PVROPR where PVROPR_MODFOR = @@MOD and PVROPR_CODFOR = @@COD and PVROPR_NROFOR = @@NRO
delete PVRMVC where PVRMVC_MODFOR = @@MOD and PVRMVC_CODFOR = @@COD and PVRMVC_NROFOR = @@NRO
delete PVRMVR where PVRMVR_MODFOR = @@MOD and PVRMVR_CODFOR = @@COD and PVRMVR_NROFOR = @@NRO
delete PVRMVG where PVRMVG_MODFOR = @@MOD and PVRMVG_CODFOR = @@COD and PVRMVG_NROFOR = @@NRO
delete PVRMVD where PVRMVD_MODFOR = @@MOD and PVRMVD_CODFOR = @@COD and PVRMVD_NROFOR = @@NRO
delete PVRMVI where PVRMVI_MODFOR = @@MOD and PVRMVI_CODFOR = @@COD and PVRMVI_NROFOR = @@NRO
delete PVRMVP where PVRMVP_MODFOR = @@MOD and PVRMVP_CODFOR = @@COD and PVRMVP_NROFOR = @@NRO
delete PVRMVH where PVRMVH_MODFOR = @@MOD and PVRMVH_CODFOR = @@COD and PVRMVH_NROFOR = @@NRO

delete CJRMVG where CJRMVG_MODFOR = @@MOD_CJ and CJRMVG_CODFOR = @@COD and CJRMVG_NROFOR = @@NRO
delete CJRMVD where CJRMVD_MODFOR = @@MOD_CJ and CJRMVD_CODFOR = @@COD and CJRMVD_NROFOR = @@NRO
delete CJRMVI where CJRMVI_MODFOR = @@MOD_CJ and CJRMVI_CODFOR = @@COD and CJRMVI_NROFOR = @@NRO
delete CJRMVH where CJRMVH_MODFOR = @@MOD_CJ and CJRMVH_CODFOR = @@COD and CJRMVH_NROFOR = @@NRO
