

INSERT INTO GRCCBF 
([GRCCBF_MODCOM]
      ,[GRCCBF_CODCOM]
      ,[GRCCBF_EMPIVA]
      ,[GRCCBF_CNDIVA]
      ,[GRCCBF_NROITM]
      ,[GRCCBF_CODEMP]
      ,[GRCCBF_MODFOR]
      ,[GRCCBF_CODFOR]
      ,[GRCCBF_CLADGI]
      ,[GRCCBF_RPTNAM]
      ,[GRCCBF_EMPFCR]
      ,[GRCCBF_MODFCR]
      ,[GRCCBF_CODFCR]
      ,[GRCCBF_MINFCR]
      ,[GRCCBF_FECALT]
      ,[GRCCBF_FECMOD]
      ,[GRCCBF_ULTOPR]
      ,[GRCCBF_DEBAJA]
      ,[GRCCBF_OALIAS]
      ,[GRCCBF_USERID])

      (SELECT DISTINCT
      [GRCCBF_MODCOM]
      ,[GRCCBF_CODCOM]
      ,GRTEMP_CODEMP
      ,GRCCBF_CNDIVA
      ,ROW_NUMBER() OVER( PARTITION BY GRCCBF_MODCOM, GRCCBF_CODCOM, GRCCBF_CODEMP , GRCCBF_MODFOR, GRCCBF_CODFOR, GRCCBF_CNDIVA ORDER BY GRCCBF_CODEMP, GRCCBF_MODCOM, GRCCBF_CODCOM , GRCCBF_MODFOR, GRCCBF_CODFOR, GRCCBF_CNDIVA  ) 
      ,GRTEMP_CODEMP
      ,[GRCCBF_MODFOR]
      ,[GRCCBF_CODFOR]
      ,grccbf_cladgi
      ,''
      ,NULL
      ,NULL
      ,NULL
      ,NULL
      ,GETDATE()
		,GETDATE()
      ,[GRCCBF_ULTOPR]
      ,[GRCCBF_DEBAJA]
      ,[GRCCBF_OALIAS]
      ,[GRCCBF_USERID]
      FROM GRTEMP, GRCCBF
      WHERE
      not exists
      (select 1 from GRCCBF t1 where
      T1.GRCCBF_MODCOM = GRCCBF.GRCCBF_MODCOM AND
      T1.GRCCBF_CODCOM = GRCCBF.GRCCBF_CODCOM AND
      T1.GRCCBF_CNDIVA = GRCCBF.GRCCBF_CNDIVA AND
      t1.GRCCBF_CODEMP = GRTEMP_CODEMP and
      t1.GRCCBF_MODFOR = GRCCBF.GRCCBF_modfor and
      t1.GRCCBF_CODFOR = GRCCBF.GRCCBF_codfor) AND
	  GRCCBF_CODEMP = 'SABAVI01' AND
      GRTEMP_CODEMP <> 'SABAVI01' AND
	  GRTEMP_ISMAIN <> 'S' 
      
      )
      
      