
INSERT INTO GRCCBS
(
	GRCCBS_MODCOM,
	GRCCBS_CODCOM,
	GRCCBS_MODCPT,
	GRCCBS_TIPCPT,
	GRCCBS_CODCPT,
	GRCCBS_DEBHAB,
	GRCCBS_ACCION,
	GRCCBS_CODEST,
	GRCCBS_FECALT,
	GRCCBS_FECMOD,
	GRCCBS_USERID,
	GRCCBS_ULTOPR,
	GRCCBS_DEBAJA,
	GRCCBS_OALIAS
)

select 

	GRCCBI_MODCOM,
	GRCCBI_CODCOM,
	GRCCBS_MODCPT,
	GRCCBS_TIPCPT,
	GRCCBS_CODCPT,
	GRCCBS_DEBHAB,
	GRCCBS_ACCION,
	GRCCBS_CODEST,
	GRCCBI_FECALT,
	GRCCBI_FECMOD,
	'GSA_INSERT',
	GRCCBI_ULTOPR,
	GRCCBI_DEBAJA,
	GRCCBS_OALIAS


from GRCCBS
INNER JOIN GRCCBI ON
GRCCBI_MODCPT = GRCCBS_MODCPT AND
GRCCBI_TIPCPT = GRCCBS_TIPCPT AND
GRCCBI_CODCPT = GRCCBS_CODCPT AND
GRCCBI_DEBHAB = GRCCBS_DEBHAB
WHERE
GRCCBS_MODCOM = 'CJ' AND
GRCCBS_CODCOM = 'OP' AND
NOT (GRCCBI_MODCOM = 'CJ' AND
GRCCBI_CODCOM = 'OP') AND
NOT EXISTS 
	(SELECT 1 FROM GRCCBS T1 
	 WHERE
		T1.GRCCBS_MODCOM = GRCCBI.GRCCBI_MODCOM AND 
		T1.GRCCBS_CODCOM = GRCCBI.GRCCBI_CODCOM AND 
		T1.GRCCBS_MODCPT = GRCCBS.GRCCBS_MODCPT AND  
		T1.GRCCBS_TIPCPT = GRCCBS.GRCCBS_TIPCPT AND 
		T1.GRCCBS_CODCPT = GRCCBS.GRCCBS_CODCPT AND 
		T1.GRCCBS_DEBHAB = GRCCBS.GRCCBS_DEBHAB AND 
		T1.GRCCBS_ACCION = GRCCBS.GRCCBS_ACCION AND
		T1.GRCCBS_CODEST = GRCCBS.GRCCBS_CODEST)
		
GROUP BY

	GRCCBI_MODCOM,
	GRCCBI_CODCOM,
	GRCCBS_MODCPT,
	GRCCBS_TIPCPT,
	GRCCBS_CODCPT,
	GRCCBS_DEBHAB,
	GRCCBS_ACCION,
	GRCCBS_CODEST,
	GRCCBI_FECALT,
	GRCCBI_FECMOD,
	GRCCBI_USERID,
	GRCCBI_ULTOPR,
	GRCCBI_DEBAJA,
	GRCCBS_OALIAS
