INSERT INTO GRTSCR (GRTSCR_LNKNAM, GRTSCR_SCRCOD, GRTSCR_WIZNAM, GRTSCR_DLLNAM, GRTSCR_NXTOBJ) VALUES ('USR_GMRMVH_USR_GMRMVH_SD', '',NULL,'USR_GMRMVH.Utilities', 'USR_GMRMVH')
INSERT INTO GRTSCR (GRTSCR_LNKNAM, GRTSCR_SCRCOD, GRTSCR_WIZNAM, GRTSCR_DLLNAM, GRTSCR_NXTOBJ) VALUES ('USR_GMTXLH_USR_GMTXLH_SD', '',NULL,'USR_GMTXLH.Utilities', 'USR_GMTXLH')
