SELECT * FROM SJTACU
WHERE
(NOT EXISTS (SELECT 1 FROM SJCCOH WHERE
SJCCOH_FORPLA LIKE '%' + SJTACU_CODACU + '%')
AND
NOT EXISTS (SELECT 1 FROM SJCCOH WHERE
SJCCOH_FORVBS LIKE '%' + SJTACU_CODACU+ '%')
AND
NOT EXISTS (SELECT 1 FROM SJTFOH WHERE
SJTFOH_FORVBS LIKE '%' + SJTACU_CODACU+ '%'))
AND
NOT EXISTS (SELECT 1 FROM SJCCOA WHERE
SJCCOA_CODACU = SJTACU_CODACU AND
SJCCOA_ACUMUL = 'S')



SELECT DISTINCT
--CHARINDEX('LEGAJO.ACUM', SJCCOH_FORPLA),
SUBSTRING(SJCCOH_FORPLA,CHARINDEX('LEGAJO.ACUM', SJCCOH_FORPLA)+13,6), SJTACU_dESCRP
--SUBSTRING(SJCCOH_FORVBS,CHARINDEX('LEGAJO.ACUM', SJCCOH_FORPLA)+13,6),
--SUBSTRING(SJTFOH_FORVBS,CHARINDEX('LEGAJO.ACUM', SJCCOH_FORPLA)+13,6),
--* 
FROM SJCCOH 
LEFT JOIN SJTFOH ON
SJCCOH_FORASO = SJTFOH_CODIGO 
LEFT JOIN SJTACU ON 
SJTACU_CODACU = SUBSTRING(SJCCOH_FORPLA,CHARINDEX('LEGAJO.ACUM', SJCCOH_FORPLA)+13,6)
WHERE 
(SJCCOH_FORPLA LIKE '%LEGAJO.ACUM%'
OR
SJTFOH_FORVBS LIKE '%LEGAJO.ACUM%'
OR
SJCCOH_FORVBS LIKE '%LEGAJO.ACUM%')
