select * from sjrmvi 
left join sjrmvg on
SJRMVI_CODEMP = SJRMVG_CODEMP AND
SJRMVI_MODFOR = SJRMVG_MODFOR AND 
SJRMVI_CODFOR = SJRMVG_CODFOR AND 
SJRMVI_NROFOR = SJRMVG_NROFOR AND
SJRMVI_EMPLEG = SJRMVG_EMPLEG AND
SJRMVI_NROLEG = SJRMVG_NROLEG AND
SJRMVI_CODCPT = SJRMVG_CODCPT
