--Agrega el ERROR.TYPE en VLOOKUP simples
UPDATE SJCCOH SET
SJCCOH_FORPLA = 'IF(ERROR.TYPE(' + CONVERT(VARCHAR(MAX),SJCCOH_FORPLA)+') = 7,0, ' + CONVERT(VARCHAR(MAX),SJCCOH_FORPLA)+ ')'
WHERE
LEN(CONVERT(VARCHAR(MAX),SJCCOH_FORPLA)) BETWEEN 161 AND 165 AND
sjccoh_forpla like '%VLOOKUP%' 

--Elimina el ERROR.TYPE
UPDATE SJCCOH SET
SJCCOH_FORPLA = REPLACE(SUBSTRING(CONVERT(VARCHAR(MAX),SJCCOH_FORPLA),15,charindex('=',CONVERT(VARCHAR(MAX),SJCCOH_FORPLA))-16),'))',')') 
WHERE
sjccoh_forpla like '%ERROR%' 



