
/*** 1. Tengo el dato de atributo en el stock pero el producto tiene configurado que no lleve el atributo****/
SELECT * FROM STRMVK
INNER JOIN STMPDH ON
STMPDH_TIPPRO = STRMVK_TIPPRO AND
STMPDH_ARTCOD = STRMVK_ARTCOD
WHERE
(STRMVK_NSERIE <> '' AND STMPDH_DEFSER = 'N') 
--OR (STRMVK_NFECHA <> '' AND STMPDH_DEFFEC = 'N') OR
--(STRMVK_NATRIB <> '' AND STMPDH_DEFATR = 'N') OR
--(STRMVK_ENVASE <> '' AND STMPDH_DEFENV = 'N') OR
--(STRMVK_NUBICA <> '' AND STMPDH_DEFUBI = 'N') OR
--(STRMVK_NOTROS <> '' AND STMPDH_DEFOTR = 'N') OR
--(STRMVK_NDESPA <> '' AND STMPDH_DEFDES = 'N') OR
--(STRMVK_NESTAN <> '' AND STMPDH_DEFEST= 'N')

/*** 1. Corrijo caso ****/
--BEGIN TRAN

--UPDATE STMPDH SET
STMPDH_DEFSER = 'P'
FROM STRMVK
INNER JOIN STMPDH ON
STMPDH_TIPPRO = STRMVK_TIPPRO AND
STMPDH_ARTCOD = STRMVK_ARTCOD
WHERE
(STRMVK_NSERIE <> '' AND STMPDH_DEFSER = 'N') 

--COMMIT TRAN

/***2. No tengo el dato de atributo en el stock pero el producto tiene configurado que lleve el atributo****/
SELECT * FROM STRMVK
INNER JOIN STMPDH ON
STMPDH_TIPPRO = STRMVK_TIPPRO AND
STMPDH_ARTCOD = STRMVK_ARTCOD
WHERE
(STRMVK_NSERIE = '' AND STMPDH_DEFSER <> 'N') OR
(STRMVK_NFECHA = '' AND STMPDH_DEFFEC <>  'N') OR
(STRMVK_NATRIB = '' AND STMPDH_DEFATR <> 'N') OR
(STRMVK_ENVASE = '' AND STMPDH_DEFENV <> 'N') OR
(STRMVK_NUBICA = '' AND STMPDH_DEFUBI <> 'N') OR
(STRMVK_NOTROS = '' AND STMPDH_DEFOTR <> 'N') OR
(STRMVK_NDESPA = '' AND STMPDH_DEFDES <> 'N') OR
(STRMVK_NESTAN = '' AND STMPDH_DEFEST <> 'N')
