DECLARE @TABLAMADRE VARCHAR(100),@TABLAHIJA VARCHAR(100)

SET @TABLAMADRE = 'CORMVI'
SET @TABLAHIJA = 'CORMVP'

SELECT FIELDNAME + ' = ' + REPLACE(FIELDNAME,@TABLAMADRE, @TABLAHIJA) + ' AND',* FROM CWTMFIELDS WHERE PrimaryKey = 1
AND
TABLENAME = @TABLAMADRE
ORDER BY FieldOrderBiZ ASC
