declare @@MOD varchar(2), @@MOD_CJ varchar(2), @@COD varchar(6), @@NRO int

 

select

@@MOD = 'VT',

@@MOD_CJ = 'CJ',

@@COD = 'RC',

@@NRO = 5109

 

SELECT * FROM VTRMVH WHERE VTRMVH_CODFOR= @@COD AND VTRMVH_NROFOR= @@NRO

 

UPDATE VTRMVH SET VTRMVH_EMPDCR=NULL,VTRMVH_MODDCR=NULL, VTRMVH_CODDCR=NULL, VTRMVH_NRODCR=NULL where VTRMVH_MODFOR = @@MOD and VTRMVH_CODFOR = @@COD and VTRMVH_NROFOR = @@NRO

 

delete VTRMVC where VTRMVC_MODFOR = @@MOD and VTRMVC_CODFOR = @@COD and VTRMVC_NROFOR = @@NRO

delete VTRMVG where VTRMVG_MODFOR = @@MOD and VTRMVG_CODFOR = @@COD and VTRMVG_NROFOR = @@NRO

delete VTRMVD where VTRMVD_MODFOR = @@MOD and VTRMVD_CODFOR = @@COD and VTRMVD_NROFOR = @@NRO

delete VTRMVI where VTRMVI_MODFOR = @@MOD and VTRMVI_CODFOR = @@COD and VTRMVI_NROFOR = @@NRO

delete VTRMVP where VTRMVP_MODFOR = @@MOD and VTRMVP_CODFOR = @@COD and VTRMVP_NROFOR = @@NRO

delete VTRMVH where VTRMVH_MODFOR = @@MOD and VTRMVH_CODFOR = @@COD and VTRMVH_NROFOR = @@NRO

 

delete CJRMVG where CJRMVG_MODFOR = @@MOD_CJ and CJRMVG_CODFOR = @@COD and CJRMVG_NROFOR = @@NRO

delete CJRMVD where CJRMVD_MODFOR = @@MOD_CJ and CJRMVD_CODFOR = @@COD and CJRMVD_NROFOR = @@NRO

delete CJRMVI where CJRMVI_MODFOR = @@MOD_CJ and CJRMVI_CODFOR = @@COD and CJRMVI_NROFOR = @@NRO

delete CJRMVH where CJRMVH_MODFOR = @@MOD_CJ and CJRMVH_CODFOR = @@COD and CJRMVH_NROFOR = @@NRO