DECLARE @NOMBRE    VARCHAR (100) 

DECLARE CURSORELECERP CURSOR FOR 

SELECT  NAME  FROM CWOMOBJECTS WHERE NAME LIKE 'USR%' AND MODULENAME = 'FC'

OPEN CURSORELECERP

Fetch Next From CURSORELECERP INTO @NOMBRE
While @@FETCH_STATUS = 0
Begin

EXEC CopiarResolucionYFormato 'FCRMVH',2, @NOMBRE

                  
Fetch Next From CURSORELECERP Into @NOMBRE
END 
Close CURSORELECERP
Deallocate CURSORELECERP
