insert into VTMCLI
(
	VTMCLI_NROCTA, 
	VTMCLI_TIPIMP, 
	VTMCLI_CORRES, 
	VTMCLI_INCLUI, 
	VTMCLI_EXEDEN, 
	VTMCLI_RESOLC, 
	VTMCLI_VIGENC, 
	VTMCLI_FCHDES, 
	VTMCLI_FECHAS, 
	VTMCLI_DISIMP, 
	VTMCLI_FECALT, 
	VTMCLI_FECMOD, 
	VTMCLI_USERID, 
	VTMCLI_ULTOPR, 
	VTMCLI_DEBAJA, 
	VTMCLI_OALIAS)
(select
	VTMCLH_NROCTA, 
	(case 
		when VTMCLI_TIPIMP = 'IVA' then 'IVA'
		when VTMCLI_TIPIMP = 'PIIBB' and VTMCLI_CORRES = 'S' then 'PIBO'
		when VTMCLI_TIPIMP = 'PIIBB' and VTMCLI_CORRES = 'N' then 'PIBE'
	end), --VTMCLI_TIPIMP, 
	'S',--VTMCLI_CORRES, 
	VTMCLI_INCLUI, 
	VTMCLI_EXEDEN, 
	VTMCLI_RESOLC, 
	VTMCLI_VIGENC, 
	VTMCLI_FCHDES, 
	VTMCLI_FECHAS, 
	VTMCLI_DISIMP, 
	VTMCLI_FECALT, 
	VTMCLI_FECMOD, 
	VTMCLI_USERID, 
	VTMCLI_ULTOPR, 
	VTMCLI_DEBAJA, 
	VTMCLI_OALIAS
from
	cwSGTrimarchisrl.dbo.VTMCLI, VTMCLH
where
	USR_VTMCLH_NROCTA = VTMCLI_NROCTA and
	not exists
	(select * from VTMCLI where VTMCLI_NROCTA = VTMCLH_NROCTA and VTMCLI_TIPIMP = (case 
																						when VTMCLI_TIPIMP = 'IVA' then 'IVA'
																						when VTMCLI_TIPIMP = 'PIIBB' and VTMCLI_CORRES = 'S' then 'PIBO'
																						when VTMCLI_TIPIMP = 'PIIBB' and VTMCLI_CORRES = 'N' then 'PIBE'
																					end))
	)


insert into VTMCLI
(
	VTMCLI_NROCTA, 
	VTMCLI_TIPIMP, 
	VTMCLI_CORRES, 
	VTMCLI_INCLUI, 
	VTMCLI_EXEDEN, 
	VTMCLI_RESOLC, 
	VTMCLI_VIGENC, 
	VTMCLI_FCHDES, 
	VTMCLI_FECHAS, 
	VTMCLI_DISIMP, 
	VTMCLI_FECALT, 
	VTMCLI_FECMOD, 
	VTMCLI_USERID, 
	VTMCLI_ULTOPR, 
	VTMCLI_DEBAJA, 
	VTMCLI_OALIAS)
select
	VTMCLH_NROCTA, 
	'PIBE', 
	'S', 
	'N', 
	0, 
	'', 
	'N', 
	'20140101', 
	'20140101', 
	'N', 
	'20140101', 
	'20140101', 
	VTMCLH_USERID, 
	VTMCLH_ULTOPR, 
	VTMCLH_DEBAJA, 
	'VTMCLI'
from
	VTMCLH
where
	not exists
	(select * from VTMCLI where VTMCLI_NROCTA = VTMCLH_NROCTA and VTMCLI_TIPIMP in ('PIBO','PIBE'))