insert into VTRMVC
(
	VTRMVC_MODFOR, 
	VTRMVC_CODFOR, 
	VTRMVC_NROFOR, 
	VTRMVC_MODAPL, 
	VTRMVC_CODAPL, 
	VTRMVC_NROAPL, 
	VTRMVC_CUOTAS, 
	VTRMVC_CLAMOV, 
	VTRMVC_FCHMOV, 
	VTRMVC_NROCTA, 
	VTRMVC_NROSUB, 
	VTRMVC_IMPTCN, 
	VTRMVC_IMPNAC, 
	VTRMVC_IMPEXT, 
	VTRMVC_FCHVNC, 
	VTRMVC_TEXTOS, 
	VTRMVC_COFLIS, 
	VTRMVC_CAMBIO, 
	VTRMVC_COFFAC, 
	VTRMVC_COFDEU, 
	VTRMVC_IMPUSS, 
	VTRMVC_CAMUSS, 
	VTRMVC_IMPSEC, 
	VTRMVC_FECALT, 
	VTRMVC_FECMOD, 
	VTRMVC_USERID, 
	VTRMVC_ULTOPR, 
	VTRMVC_DEBAJA, 
	VTRMVC_OALIAS, 
	VTRMVC_CODEMP
)
(
select
	VTRMVC_MODAPL, 		--	VTRMVC_MODFOR, 
	VTRMVC_CODAPL, 		--	VTRMVC_CODFOR, 
	VTRMVC_NROAPL, 		--	VTRMVC_NROFOR, 
	VTRMVC_MODAPL, 		--	VTRMVC_MODAPL, 
	VTRMVC_CODAPL, 		--	VTRMVC_CODAPL, 
	VTRMVC_NROAPL, 		--	VTRMVC_NROAPL, 
	VTRMVC_CUOTAS, 		--	VTRMVC_CUOTAS, 
	max(VTRMVC_CLAMOV), 		--	VTRMVC_CLAMOV, 
	min(VTRMVC_FCHMOV), 		--	VTRMVC_FCHMOV, 
	VTRMVH_NROCTA, 		--	VTRMVC_NROCTA, 
	VTRMVH_NROSUB, 		--	VTRMVC_NROSUB, 
	VTRMVH_IMPTCN, 		--	VTRMVC_IMPTCN, 
	sum(VTRMVC_IMPNAC), 		--	VTRMVC_IMPNAC, 
	sum(VTRMVC_IMPEXT), 		--	VTRMVC_IMPEXT, 
	VTRMVC_FCHVNC, 		--	VTRMVC_FCHVNC, 
	'Saldo Inicial', 		--	VTRMVC_TEXTOS, 
	VTRMVH_COFLIS, 		--	VTRMVC_COFLIS, 
	VTRMVH_CAMBIO, 		--	VTRMVC_CAMBIO, 
	VTRMVH_COFFAC, 		--	VTRMVC_COFFAC, 
	VTRMVH_COFDEU, 		--	VTRMVC_COFDEU, 
	sum(VTRMVC_IMPUSS), 		--	VTRMVC_IMPUSS, 
	VTRMVH_CAMBIO, 		--	VTRMVC_CAMUSS, 
	sum(VTRMVC_IMPSEC), 		--	VTRMVC_IMPSEC, 
	getdate(), 		--	VTRMVC_FECALT, 
	getdate(), 		--	VTRMVC_FECMOD, 
	'SAR_MIG', 		--	VTRMVC_USERID, 
	'A', 		--	VTRMVC_ULTOPR, 
	'N', 		--	VTRMVC_DEBAJA, 
	'VTRMVC', 		--	VTRMVC_OALIAS, 
	VTRMVH_CODEMP	--	VTRMVC_CODEMP
from
	VTRMVH, cwSGTrimarchisrl.dbo.VTRMVC
where
	VTRMVH_MODFOR = VTRMVC_MODAPL and
	VTRMVH_CODFOR = VTRMVC_CODAPL and
	VTRMVH_NROFOR = VTRMVC_NROAPL and
	not exists
	(select 1 from VTRMVC
	where
		cwSGTrimarchisrl.dbo.VTRMVC.VTRMVC_MODAPL = VTRMVC.VTRMVC_MODAPL and
		cwSGTrimarchisrl.dbo.VTRMVC.VTRMVC_CODAPL = VTRMVC.VTRMVC_CODAPL and
		cwSGTrimarchisrl.dbo.VTRMVC.VTRMVC_NROAPL = VTRMVC.VTRMVC_NROAPL)
group by
	VTRMVC_MODAPL, 		--	VTRMVC_MODFOR, 
	VTRMVC_CODAPL, 		--	VTRMVC_CODFOR, 
	VTRMVC_NROAPL, 		--	VTRMVC_NROFOR, 
	VTRMVC_MODAPL, 		--	VTRMVC_MODAPL, 
	VTRMVC_CODAPL, 		--	VTRMVC_CODAPL, 
	VTRMVC_NROAPL, 		--	VTRMVC_NROAPL, 
	VTRMVC_CUOTAS, 		--	VTRMVC_CUOTAS, 
	VTRMVH_NROCTA, 		--	VTRMVC_NROCTA, 
	VTRMVH_NROSUB, 		--	VTRMVC_NROCTA, 
	VTRMVH_IMPTCN, 		--	VTRMVC_IMPTCN, 
	VTRMVC_FCHVNC, 		--	VTRMVC_FCHVNC, 
	VTRMVH_COFLIS, 		--	VTRMVC_COFLIS, 
	VTRMVH_CAMBIO, 		--	VTRMVC_CAMBIO, 
	VTRMVH_COFFAC, 		--	VTRMVC_COFFAC, 
	VTRMVH_COFDEU, 		--	VTRMVC_COFDEU, 
	VTRMVH_CAMBIO, 		--	VTRMVC_CAMUSS, 
	VTRMVH_CODEMP	--	VTRMVC_CODEMP
)
